

start: ( form )+

PLUS: "+"
MINUS: "-"
MULT: "*"
DIV: "/"
MOD: "%"

boolean: "true" | "false"

value: string   
     | number 
     | boolean 

variable: name ":" value

operator: (PLUS | MINUS | MULT | DIV | MOD)

expression: name
          | number              
          | name operator expression
          | number operator expression
          | expression operator expression

formula: name "=" expression

field: (variable | formula)+

form: name ":" "{" (field)+ "}"

name    : CNAME
string  : ESCAPED_STRING
number  : SIGNED_NUMBER


%import common.ESCAPED_STRING   
%import common.SIGNED_NUMBER
%import common.CNAME 
%import common.WS
%ignore WS 