

start: ( form )+

boolean: "true" | "false"

value: string   
     | number 
     | boolean 

variable: name ":" value

operator: "+" | "-" | "/" | "*" | "%"

expression: string operator (variable | expression)

formula: string "=" expression

field: ( variable | formula )+

form: name ":" "{" ( field )+ "}"

name   : CNAME
string : ESCAPED_STRING
number : SIGNED_NUMBER

%import common.ESCAPED_STRING   
%import common.SIGNED_NUMBER
%import common.CNAME 
%import common.WS
%ignore WS 